const express =require("express")
const routes=express.Router()
const{register,login,logOut}=require("../Auth/LoginRegister.")
const{UploadProduct,allProductes}=require("../Controllers/productController")
routes.post("/register",register)
routes.post("/login",login)  
routes.get("/logOut",logOut)  
routes.post("/product",UploadProduct)
routes.get("/allproduct",allProductes)
module.exports={routes}