import React from 'react'
import about from "./about.gif"

export default function About() {
  return (
    <div className='flex justify-center items-center  flex-col' >
<img className='w-[50rem]  items-center h-[35rem] mt-[80px]  ' src={about} alt="" />
<div className='bg-red-100 bottom-0 text-lg px-10 py-5 font-bold top-[300px] '>
  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus suscipit distinctio dolor asperiores similique natus possimus, quae minus, pariatur consequatur ipsum ex hic easdasrror necessitatibus unde sit magni, atque dolorem et reprehenderit beatae sed aliquid autem! Perferendis autem deserunt, odio esse tempore voluptatibus at culpa quas in nostrum minima laudantium recusandae, harum corrupti consequatur id tenetur rerum odit molestiae dicta? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptate, impedit molestiae vitae delectus dolor id dolore, libero ab ex neque voluptatem! Eum maiores ea labore accusamus soluta fuga esse sapiente blanditiis vero facere, ut quis nulla, illum quia delectus maxime. Natus sint corrupti ad sed sequi explicabo maxime, placeat tenetur perferendis saepe praesentium eaque odio! Id omnis nobis facere numquam a sapiente expedita libero tenetur maiores possimus repudiandae illum, sed aliquid cupiditate magni sequi similique laborum voluptas. Velit voluptates animi debitis repudiandae totam quibusdam magni  accusantium expedita eum assumenda maxime adipisci. Repellendus iure commodi, ea nulla illum asperiores suscipit quae quia nesciunt quo quaerat iusto voluptas alias accusantium maiores provident illo expedita ipsam, delectus doloremque nobis fuga consequatur sit. Neque perspiciatis hic, magni quas omnis laboriosam, quasi quaerat cupiditate laborum praesentium cumque ad vitae tempora veniam laudantium asperiores repellendus expedita doloribus quod consectetur ut. Ipsam minima voluptatum earum rerum laboriosam, ipsa magnam qui molestiae. Earum commodi laboriosam qui, modi necessitatibus labore, voluptate delectus autem sit tempora vel libero maiores tempore illum provident voluptatibus. Voluptatem voluptatibus laborum, quidem est expedita sed corporis corrupti, numquam, voluptates cupiditate minus. Asperiores, facere id nemo reiciendis illo vitae maxime fugit error ipsam quae consequuntur minus explicabo dicta quis voluptate sit alias soluta accusamus quas impedit at! Officiis, praesentium quos quaerat amet excepturi iusto dolor ducimus asperiores eligendi. Dicta quaerat inventore repudiandae iusto rem cupiditate possimus magnam rerum, voluptates eos nemo adipisci sequi saepe ad voluptate est fugit fuga, qui sunt voluptatum facere nostrum, id veniam obcaecati! Amet consequatur excepturi incidunt vero, 
</div>
    </div>
  )
}
